# -*- coding: utf-8 -*-
"""Deeplearning_Project_text_normalization_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mdz6EbqxMVwFHox8R87yLeFZlDkN4yqc
"""

!pip install transformers datasets

import re
import random
from datasets import load_dataset, Dataset, DatasetDict
from transformers import T5Tokenizer,Seq2SeqTrainer, Seq2SeqTrainingArguments, EarlyStoppingCallback
import pandas as pd
import itertools
from typing import List, Dict, Optional
import nltk
from nltk.tokenize import sent_tokenize
import requests
import json
import numpy as np
import torch
from datasets import load_from_disk
from transformers import (
    T5Tokenizer,
    T5Config,
    T5ForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq
)
import torch.nn as nn
from transformers.modeling_outputs import BaseModelOutput

from google.colab import drive
drive.mount('/content/drive')

def create_unpunctuated_text(text: str) -> str:
    """Remove punctuation and capitalization from text"""
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def add_extra_spaces(text: str) -> str:
    """Add extra spaces randomly"""
    words = text.split()
    result = []
    for word in words:
        result.append(word)
        if random.random() < 0.3:  # 30% chance to add extra space
            result.append(' ')
    return ' '.join(result)

def remove_some_spaces( text: str) -> str:
    """Remove some spaces randomly"""
    words = text.split()
    result = []
    for i, word in enumerate(words):
        result.append(word)
        if i < len(words) - 1 and random.random() < 0.2:  # 20% chance to remove space
            continue
        else:
            result.append(' ')
    return ''.join(result).strip()

def mix_case_randomly(text: str) -> str:
    """Randomly mix uppercase and lowercase"""
    return ''.join(c.upper() if random.random() < 0.1 else c.lower() for c in text)


def load_wikipedia_dataset(language: str = "en", max_samples: Optional[int] = 10000):
    nltk.download('punkt')
    nltk.download('punkt_tab')
    try:
        wiki_dataset = load_dataset("wikimedia/wikipedia", f"20231101.{language}", split="train", streaming=True)

        samples = []
        count = 0

        for example in wiki_dataset:
            if max_samples and count >= max_samples:
                break

            text = example['text']
            sentences = sent_tokenize(text)

            for sentence in sentences:
                if len(sentence.split()) > 5:
                    # Apply transformations sequentially
                    input_text = create_unpunctuated_text(sentence)
                    input_text = add_extra_spaces(input_text)
                    input_text = remove_some_spaces(input_text)
                    input_text = mix_case_randomly(input_text)

                    if input_text.strip() and input_text != sentence:
                        samples.append({
                            "input_text": f"normalize: {input_text}",
                            "target_text": sentence
                        })
                        count += 1

            if count % 1000 == 0:
                print(f"Processed {count} samples...")

        dataset = Dataset.from_list(samples)
        print(f" Created Wikipedia dataset with {len(dataset)} samples")
        return dataset

    except Exception as e:
        print(f"Error loading Wikipedia dataset: {e}")
        return None


wiki_dataset = load_wikipedia_dataset(max_samples=100000)
train_test_split = wiki_dataset.train_test_split(test_size=0.2, seed=42)

print(f"\nFinal dataset statistics:")
print(f"Training samples: {len(train_test_split['train'])}")
print(f"Validation samples: {len(train_test_split['test'])}")

# Save datasets
train_test_split['train'].save_to_disk("./large_text_normalization_train")
train_test_split['test'].save_to_disk("./large_text_normalization_val")

# Show sample
print("\nSample from dataset:")
for i in range(3):
    sample = train_test_split['train'][i]
    print(f"Input:  {sample['input_text']}")
    print(f"Output: {sample['target_text']}")
    print()

train_dataset = load_from_disk("/content/large_text_normalization_train")
test_dataset  = load_from_disk("/content/large_text_normalization_val")


model_name = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)


def preprocess(examples):
    inputs = examples["input_text"]
    targets = examples["target_text"]

    model_inputs = tokenizer(inputs,
                             truncation=True, padding="max_length",max_length=256)

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets,
                           truncation=True, padding="max_length",max_length=256)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_dataset = train_dataset.map(preprocess, batched=True)
test_dataset  = test_dataset.map(preprocess, batched=True)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

# Adjust sample sizes based on available compute
small_train = train_dataset.shuffle(seed=42).select(range(10000))
small_val = test_dataset.shuffle(seed=42).select(range(1000))

# Define Hyperparameter Grid
learning_rates = [5e-5, 1e-4, 3e-4]
weight_decays = [0.01, 0.05]
label_smooths = [0.0, 0.1]

results = []

# Run Each Combination

for lr, wd, ls in itertools.product(learning_rates, weight_decays, label_smooths):
    print(f"\n Training with lr={lr}, weight_decay={wd}, label_smoothing={ls}")

    training_args = Seq2SeqTrainingArguments(
        #output_dir=f"./t5_tuning/lr{lr}_wd{wd}_ls{ls}",
        eval_strategy ="steps",
       # save_strategy="epoch",
       # save_total_limit=1,                  # Keep only last checkpoint
        learning_rate=lr,
        weight_decay=wd,
        num_train_epochs=3,                  # Slightly higher for early stopping to kick in
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        warmup_ratio=0.1,
        logging_strategy="epoch",
        predict_with_generate=False,         # Speed up evaluation
        fp16=True,                           # Mixed precision
        label_smoothing_factor=ls,
        #load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        report_to="none",                    # Disable external logging (wandb/tensorboard)
    )

    # Define trainer with early stopping callback
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=small_train,
        eval_dataset=small_val,
        tokenizer=tokenizer,
        data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]  # stops after 2 evals without improvement
    )

    trainer.train()
    eval_results = trainer.evaluate()
    eval_loss = eval_results["eval_loss"]

    print(f" Finished: eval_loss = {eval_loss:.4f}")
    results.append((lr, wd, ls, eval_loss))

#Identify Best Combination

best = min(results, key=lambda x: x[3])
print("\n Best Hyperparameter Combination:")
print(f"Learning Rate: {best[0]}")
print(f"Weight Decay:  {best[1]}")
print(f"Label Smooth:  {best[2]}")
print(f"Eval Loss:     {best[3]:.4f}")

# def compute_metrics(eval_pred):
#     predictions, labels = eval_pred

#     # Decode
#     preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
#     labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
#     refs = tokenizer.batch_decode(labels, skip_special_tokens=True)

#     # Exact string match accuracy
#     correct = sum(p.strip() == r.strip() for p, r in zip(preds, refs))
#     acc = correct / len(preds)

#     return {"accuracy": acc}

# using the hypo parameters from the best perfroming model in above step
Learning_Rate= 3e-4
Weight_Decay=  0.01
Label_Smooth=  0.0

training_args = Seq2SeqTrainingArguments(
    output_dir="/content/drive/MyDrive/t5-text-normalization/",
    eval_strategy ="steps",
    eval_steps=1000,
    save_strategy="epoch",
    learning_rate=Learning_Rate,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    label_smoothing_factor=Label_Smooth,
    weight_decay=Weight_Decay,
    save_total_limit=2,
    num_train_epochs=10,
    predict_with_generate=True,
    logging_dir="./logs",
    logging_steps=100,
    report_to="none"
)


trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
   # compute_metrics=compute_metrics
)

trainer.train()

print("Evaluating on test set...")
results = trainer.evaluate()
print(results)

import matplotlib.pyplot as plt
import pandas as pd

def plot_hf_training_logs(trainer):
    # Convert log history to DataFrame
    logs = pd.DataFrame(trainer.state.log_history)

    # Filter only rows with loss values
    train_logs = logs[logs["loss"].notnull()]
    eval_logs = logs[logs["eval_loss"].notnull()]

    # Extract values
    train_loss = train_logs["loss"].values
    eval_loss = eval_logs["eval_loss"].values
    train_epochs = train_logs["epoch"].values
    eval_epochs = eval_logs["epoch"].values

    # Plot Training & Evaluation Loss
    plt.figure(figsize=(8, 5))
    plt.plot(train_epochs, train_loss, "bo-", label="Training Loss")
    plt.plot(eval_epochs, eval_loss, "ro-", label="Evaluation Loss")
    plt.title("Training and Evaluation Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    plt.show()

plot_hf_training_logs(trainer)