# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkD2Smh_fvYJvF19HvEQdseE4wCMBEWA
"""

from google.colab import drive
drive.mount('/content/drive')

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
import textwrap

# Load model
model_path = "/content/drive/MyDrive/t5-text-normalization/checkpoint-20008/checkpoint-20008/"   # adjust to your path
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

# Input transcript
raw_transcript = """
every journey begins with a single moment of courage when a persondecides to step beyondthe familiar and chasesomething greater than comfort the road ahead is never certain and the heart may tremble with doubt but with each step the fear fades and strength grows along the way there are people who offer kindness lessons that shape the soul and challenges that reveal what truly matters time moves like a river carrying dreams hopes and memories and even when the path feels endless the spirit learns to find beauty in the struggle meaning in the silence and light in the darkest corners of the journey"""

# Prefix "normalize:" if your training used that
input_text = "normalize: " + raw_transcript.strip()

# Tokenize input
inputs = tokenizer(input_text, return_tensors="pt", truncation=True)

# Generate output
with torch.no_grad():
    generated_ids = model.generate(
    **inputs,
    max_length=1024,
    do_sample=True,
    top_k=50,
    top_p=0.95,
    temperature=0.9
)

chunks = textwrap.wrap(raw_transcript, 400)
normalized_chunks = []
for ch in chunks:
    input_text = "normalize: " + ch
    inputs = tokenizer(input_text, return_tensors="pt", truncation=True)
    output_ids = model.generate(**inputs, max_length=256, num_beams=5)
    normalized_chunks.append(tokenizer.decode(output_ids[0], skip_special_tokens=True))

final_output = " ".join(normalized_chunks)

print("===== RAW TRANSCRIPT =====")
print(raw_transcript)
print("\n===== NORMALIZED OUTPUT =====")
print(final_output)